### ISSUE TITLE
Can no longer update from repo

### ISSUE THREAD

**Issue by Jesspu** [zbirenbaum/copilot-cmp#14]
Hey, I recently tried to update (Packer Sync), and the packer update failed repeatedly. 

After some digging, it seems like there was maybe a rebase of the main branch, which packer did not like. So, I went to the repo directory in packer, and tried to do `git pull --allow-unrelated-histories, so I could update from the main branch. 

However, the auto merge failes

```
Auto-merging lua/copilot_cmp/init.lua
CONFLICT (add/add): Merge conflict in lua/copilot_cmp/init.lua
Auto-merging lua/copilot_cmp/source.lua
CONFLICT (add/add): Merge conflict in lua/copilot_cmp/source.lua
Automatic merge failed; fix conflicts and then commit the result.
```

Do I just need to uninstall and reinstall this plugin?

**Comment by zbirenbaum** [comment]
That's interesting, as I haven't run into any problems like that.

Just rm -rf the copilot-cmp directory wherever packer installs it, then packersync again. It should be this by default:
`~/.local/share/nvim/pack/packer/{start or opt}/copilot-cmp`

**Comment by Jesspu** [comment]
That fixed it, thanks.
