### ISSUE TITLE
copilot source registered multiple times.

### ISSUE THREAD

**Issue by dsully** [zbirenbaum/copilot-cmp#2]
Running `:CmpStatus` shows:

```
# ready source names
- dictionary
- nvim_lsp_document_symbol
- nvim_lsp_signature_help
- nvim_lua
- buffer
- path
- luasnip
- nvim_lsp:null-ls
- copilot
- copilot
- nvim_lsp:sumneko_lua
- copilot
- copilot
```

It appears any time an `InsertEnter` event occurs, the source is added. Perhaps using `once` would address the issue.

**Comment by zbirenbaum** [comment]
Thanks for the catch, this shouldn't be the case and I'm not sure why it is. I'll look into it.

**Comment by zbirenbaum** [comment]
This seems to be fixed for me after the latest patches, please reopen if the issue pops back up.

**Comment by dsully** [comment]
Looks better.. I am seeing this message now though:

`method setEditorInfo is not supported by any of the servers registered for the current buffer`

**Comment by zbirenbaum** [comment]
> Looks better.. I am seeing this message now though:
> 
> 
> 
> `method setEditorInfo is not supported by any of the servers registered for the current buffer`

Update and try now

**Comment by dsully** [comment]
That fix worked.

**Comment by dsully** [comment]
I spoke too soon:

<img width="1390" alt="CleanShot 2022-04-06 at 18 25 48@2x" src="https://user-images.githubusercontent.com/22371/162101738-e3875813-5ed2-4790-9b9b-f7d0399fe7ba.png">

From `:LspInfo`
