### ISSUE TITLE
Duplicate text after insertion

### ISSUE THREAD

**Issue by GuillaumeAllain** [zbirenbaum/copilot-cmp#22]
I have a slight issue that I've only been able to track to this plugin, however it might still be in my cmp config.

For example if I have

```.python
import numpy
numpy.array(|)
```

The cursor being the `|` character, the copilot suggestion is `numpy.array([1, 2, 3])`, however when I insert this suggestion, I obtain:

```.python
import numpy
bumpy.array([1, 2, 3]))
```

It duplicates the closing parentheses, this is both with Insert and Replace behaviour in cmp.

**Comment by zbirenbaum** [comment]
Sorry this took so long to get back about. I added an option to address this called `clear_after_cursor`. If it seems stable enough I will set it to be the default, but for now it is opt in. Try it out and let me know how it goes.

**Comment by GuillaumeAllain** [comment]
Yes, this solves the issue I was having. Thanks!
