### ISSUE TITLE
Indentation wrong on first line of mutli-line and all single line completions

### ISSUE THREAD

**Issue by cwebster2** [zbirenbaum/copilot-cmp#23]
I'm not sure if this is something with my cmp config, but i'm only seeing it with this source.

I'm being offered a multi-line copilot completion
![image](https://user-images.githubusercontent.com/5762261/188183924-632c92a6-2186-4316-adde-dc0ee93046b8.png)

and once selected
![image](https://user-images.githubusercontent.com/5762261/188184139-c25c5a24-a86b-41ae-ad31-93b707326e55.png)

everything shows up properly except the first line which becomes un-indented.  I see this on *all* my copilot completions and single line completions are always un-indented.

my cmp setup is here: https://github.com/cwebster2/vim/blob/nvim-lua/lua/cwebster/completion/cmp.lua
my copilot-cmp setup is here: https://github.com/cwebster2/vim/blob/05a6fac5fe6a433c19fbb488f4dcb12972521bbf/lua/cwebster/copilot.lua#L12

**Comment by zbirenbaum** [comment]
This should never occur. I do some advanced indentation logic to try and fix some of copilot's issues, which includes removing the first/last line indentation set by copilot and offsetting it by current cursor location. There are a ton of indentation issues being brought up, so I'll add this to the list of things to check for, but I'm not sure how to reproduce it.

Could you provide your indentation related neovim options?

**Comment by cwebster2** [comment]
I've tried `vim.opt.autoindent` in both true and false.  My formatoptions has -t and +n.  smartindent is true (false diesnt change the behavior). 

I have tressiter indent enabled as well, but didnt see a difference with it disabled.

I dont think I have any other indentation settings, but I could be missing something.  If you have an ideas on things to check or that have caused issues for others, i'm happy to experiment.

**Comment by cwebster2** [comment]
I should also point out I'm on neovim nightly.

**Comment by zbirenbaum** [comment]
I just pushed a large update which dramatically improved the formatting functions and allows micromanagement of formatting via overrides. If your issue is not solved by the changes to the defaults, you can write your own formatting function to fix it for your particular setup. Unfortunately my attempts to create catch all solutions for everyone's setup have not been very successful, so I decided I would no longer try to. There are too many edge cases to consider and variables at play :(

**Comment by cwebster2** [comment]
Your latest commit seems to have fixed my indentation issues.  Thanks for your work on this plugin!
