### ISSUE TITLE
Recent update broke copilot source?

### ISSUE THREAD

**Issue by Alvinferdi990** [zbirenbaum/copilot-cmp#27]
After recent update the cmp source is not being used.
![image](https://user-images.githubusercontent.com/111579117/189635603-eaa495fd-8d9e-4a1c-af12-7b8318904343.png)

![image](https://user-images.githubusercontent.com/111579117/189636465-49f12ab8-3624-4a33-a2e7-aacc5e2cb0bb.png)
Copilot server is active

I am using nvim 0.7.2, copilot.vim files are present. I am also using nvchad. 

Plugins are required like this:
```
["zbirenbaum/copilot.lua"] = {
    after = { "nvim-lspconfig" },
    config = function()
      require("copilot").setup {}
    end,
    -- disable = true,
  },
  ["zbirenbaum/copilot-cmp"] = {
    after = { "copilot.lua" },
    config = function()
      require("copilot_cmp").setup()
    end,
  },
```

Cmp config: 
```
M.cmp = function()
  local cmp = require "cmp"
  return {
    experimental = {
      ghost_text = true,
    },
    preselect = cmp.PreselectMode.None,
    sources = {
      { name = "copilot", group_index = 2 },
      { name = "nvim_lsp", group_index = 2 },
      { name = "nvim_lua", group_index = 2 },
      { name = "luasnip", group_index = 2 },
      { name = "buffer", group_index = 2 },
      { name = "path", group_index = 2 },
    },
    mappings = {
      ["<CR>"] = cmp.mapping.confirm {
        behavior = cmp.ConfirmBehavior.Replace,
        select = false,
      },
    },
    formatting = {
      format = function(entry, vim_item)
        local icons = require("nvchad_ui.icons").lspkind
        if entry.source.name == "copilot" then
          vim_item.kind = "  Copilot"
          vim_item.kind_hl_group = "CmpItemKindCopilot"
          return vim_item
        end
        vim_item.kind = string.format("%s %s", icons[vim_item.kind], vim_item.kind)
        return vim_item
      end,
    },
    sorting = {
      priority_weight = 2,
      comparators = {

        require("copilot_cmp.comparators").prioritize,
        require("copilot_cmp.comparators").score,

        cmp.config.compare.offset,
        cmp.config.compare.exact,

        -- Below is the default comparitor list and order for nvim-cmp
        cmp.config.compare.score,
        cmp.config.compare.recently_used,
        cmp.config.compare.locality,
        cmp.config.compare.kind,
        cmp.config.compare.sort_text,
        cmp.config.compare.length,
        cmp.config.compare.order,
      },
    },
  }
end
```

**Comment by crisidev** [comment]
I have the same issue.

**Comment by zbirenbaum** [comment]
Can you try putting "nvim-cmp" inside the 'after' field of copilot-cmp and see if that fixes it?

**Comment by crisidev** [comment]
I figured out there was an API change and I was not calling `require("copilot_cmp").setup()`. It's working now.

**Comment by zbirenbaum** [comment]
> I figured out there was an API change and I was not calling `require("copilot_cmp").setup()`. It's working now.

Yeah, hopefully thats the issue for @Alvinferdi990 too. Sorry about the breaking change. I really didn't want to make one but I didn't have much of a choice if I wanted to keep things organized :(

**Comment by Alvinferdi990** [comment]
Weird, but it did not help. My plugin init now looks like this, but the source is still unused. Packer sync was done after.
```
["zbirenbaum/copilot.lua"] = {
    after = { "nvim-lspconfig" },
    config = function()
      require("copilot").setup {}
    end,
    -- disable = true,
  },
  ["zbirenbaum/copilot-cmp"] = {
    after = { "copilot.lua", "nvim-cmp" },
    config = function()
      require("copilot_cmp").setup()
    end,
  },
```

**Comment by zbirenbaum** [comment]
> Weird, but it did not help. My plugin init now looks like this, but the source is still unused. Packer sync was done after.
> 
> ```
> 
> ["zbirenbaum/copilot.lua"] = {
> 
>     after = { "nvim-lspconfig" },
> 
>     config = function()
> 
>       require("copilot").setup {}
> 
>     end,
> 
>     -- disable = true,
> 
>   },
> 
>   ["zbirenbaum/copilot-cmp"] = {
> 
>     after = { "copilot.lua", "nvim-cmp" },
> 
>     config = function()
> 
>       require("copilot_cmp").setup()
> 
>     end,
> 
>   },
> 
> ```
> 
> 

Just to be safe, you have gone into insert mode before checking right?

I'm really struggling to figure out what it could be here. Would you mind double checking your node version as well?

**Comment by Alvinferdi990** [comment]
I did, selected a few lsp completions, but there source is still unused. I tried calling the setup function manually (and deleting the config part of copilot_cmp) also to no effect. 
I think there might be a bug with nvchad "legacy" variant for overriding the default plugin configs. Id have to try the new way, maybe that will fix it.

**Comment by zbirenbaum** [comment]
> I did, selected a few lsp completions, but there source is still unused. I tried calling the setup function manually (and deleting the config part of copilot_cmp) also to no effect. 
> 
> I think there might be a bug with nvchad "legacy" variant for overriding the default plugin configs. Id have to try the new way, maybe that will fix it.  

Super quick and dirty way to test this is just paste your config over the file NvChad calls

**Comment by Alvinferdi990** [comment]
Yeah that did it. The old way for overriding works partially now, it seems. Sorry for bothering you.

**Comment by Alvinferdi990** [comment]
Just added the source into the nvchad file and it worked.

**Comment by zbirenbaum** [comment]
> Just added the source into the nvchad file and it worked.

If it makes you feel any better im a core dev of NvChad and I don't even typically update my config to work for at least a month or two after breaking changes...
