### ISSUE TITLE
Suggestion does not show for some language

### ISSUE THREAD

**Issue by y9c** [zbirenbaum/copilot-cmp#34]
After setup this plugin. Copilot works properly in one of my machines. But in WLS2 of windows system. Copilot dose not output any suggestions for some of the languages (python, perl, etc.), while other language works properly. 

[![asciicast](https://asciinema.org/a/qo1gpyTPPFqn8IMeorDw0kIgO.svg)](https://asciinema.org/a/qo1gpyTPPFqn8IMeorDw0kIgO)

**Comment by y9c** [comment]
This bug  should be in `copilot.lua` or `copilot.vim` side. 

The wasm in https://github.com/zbirenbaum/copilot.lua/tree/master/copilot/dist might cause the error.  Language with wasm file can not start copilot correctly.

**Comment by yngwi** [comment]
Hi, I'm having a similar problem: most languages seem to work fine (for instance php) but I can't get suggestions for Javascript / Typescript. Is there anything I can do on my end to fix this? Thanks!

**Comment by zbirenbaum** [comment]
> Hi, I'm having a similar problem: most languages seem to work fine (for instance php) but I can't get suggestions for Javascript / Typescript. Is there anything I can do on my end to fix this? Thanks!

There were some updates today that might resolve this, try syncing and see. If it's still broken open an issue in copilot.lua

**Comment by willian** [comment]
I synced and it is not working for me as well. It works with `.lua`, but not with JavaScript / TypeScript files

**Comment by zbirenbaum** [comment]
@willian @yngwi Make sure the node version you use with copilot.lua 16. 9/10 times that is the problem, higher versions don’t work properly.

**Comment by yngwi** [comment]
Indeed it was my problem. now everything works just fine.

**Comment by catgoose** [comment]
> @willian @yngwi Make sure the node version you use with copilot.lua 16. 9/10 times that is the problem, higher versions don’t work properly.

Would there be problems using mode 14.20?  I can't get copilot suggestions to populate  and I wonder if that's the issue.
