### ISSUE TITLE
Constant format.lua errors

### ISSUE THREAD

**Issue by ariel-frischer** [zbirenbaum/copilot-cmp#36]
I seem to get this when I'm just typing but it comes on and off randomly hard to duplicate.
```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
```

```
Error executing vim.schedule lua callback: ...e/pack/packer/opt/copilot-cmp/lua/copilot_cmp/format.lua:61: Index out of bounds
stack traceback:
	[C]: in function 'nvim_buf_get_text'
	...e/pack/packer/opt/copilot-cmp/lua/copilot_cmp/format.lua:61: in function 'get_line_text'
	...e/pack/packer/opt/copilot-cmp/lua/copilot_cmp/format.lua:76: in function 'format_fn'
	...e/pack/packer/opt/copilot-cmp/lua/copilot_cmp/format.lua:97: in function 'insert_text'
	...opt/copilot-cmp/lua/copilot_cmp/completion_functions.lua:7: in function <...opt/copilot-cmp/lua/copilot_cmp/completion_functions.lua:6>
	vim/shared.lua: in function 'tbl_map'
	...opt/copilot-cmp/lua/copilot_cmp/completion_functions.lua:39: in function 'format_completions'
	...opt/copilot-cmp/lua/copilot_cmp/completion_functions.lua:61: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by zbirenbaum** [comment]
I just pushed an update a minute ago. Would you mind syncing and see if it still pops up?

**Comment by ariel-frischer** [comment]
Sounds good will give update later today.

**Comment by zbirenbaum** [comment]
> Sounds good will give update later today.

Thanks, if it still occurs please include an updated screenshot so I have an easy reference for the line numbers

**Comment by yngwi** [comment]
Hi, not sure if it's about the same problem, but `fmt_info` sounds like it is related to formatting. I'm getting this error message:

![image](https://user-images.githubusercontent.com/963440/195293873-c2749cd2-7e78-432f-8053-0a88083d09fc.png)

**Comment by ariel-frischer** [comment]
Haven't gotten that error since updating but I still feel like its a bit too soon to close. Will keep you posted :)

**Comment by zbirenbaum** [comment]
> Haven't gotten that error since updating but I still feel like its a bit too soon to close. Will keep you posted :)

The only outstanding reference to that function was in force_autofmt, which I just removed since it was a hacky solution to problems microsoft introduced prior but have changed in nature.
