### ISSUE TITLE
Question about formatting removing parens

### ISSUE THREAD

**Issue by ChristianChiarulli** [zbirenbaum/copilot-cmp#38]
should I add this to the copilot-cmp setup function or the cmp setup function?

**Comment by zbirenbaum** [comment]
> should I add this to the copilot-cmp setup function or the cmp setup function?

Could you clarify exactly what you are trying to achieve? Recently a lot of options were streamlined or outright removed after various changes in both cmp and copilot itself rendered many of them either redundant or outright broken.

Any option for copilot cmp will typically be part of the copilot-cmp setup function though, the couple of things that have to go in the cmp config it's stated explicitly that they go there, and the examples will show the cmp setup function.
