### ISSUE TITLE
Toggle completion source

### ISSUE THREAD

**Issue by MoritzBoehme** [zbirenbaum/copilot-cmp#48]
Hey,
I'm currently trying to toggle the completion from copilot on or off, but it seems, that even when toggling to off the completion from copilot.lua, cmp still uses copilot as a source.
Is there any way to toggle the source on or off?

**Comment by MunifTanjim** [comment]
Should be possible once https://github.com/zbirenbaum/copilot.lua/pull/127 gets merged.

**Comment by MoritzBoehme** [comment]
This solved my issue. Thanks 👍
