### ISSUE TITLE
Is there any way to control the number of copilot suggestions?

### ISSUE THREAD

**Issue by IndianBoy42** [zbirenbaum/copilot-cmp#52]
Right now i get 2 in the menu, I want to experiment with having more or less

**Comment by zbirenbaum** [comment]
Yes and no. No, copilot-cmp is not filtering out suggestions or anything. It is just giving what copilot returns.

Yes, copilot has a flag which can be used to set the number of completions requested.

No, the flag does not work when setting it as you would any standard LSP option as far as I could tell in tests, nor have I been able to get it working without hardcoding it into the server. If it was easily doable I would already have implemented this, trust me.
