### ISSUE TITLE
How can I get suggestions without ending the word?

### ISSUE THREAD

**Issue by benlieb** [zbirenbaum/copilot-cmp#56]
I'm only getting suggestions when I press space or some other character like `(` or `{` that ends the word. 

I'd like to get suggestions when I pause in the middle of a word or something similar.

Is this configurable?

**Comment by benlieb** [comment]
I tried 

```lua
  sources = {
    { name = "copilot", group_index = 1, trigger_characters = { ... }  },
  }
```

And added in alphabet characters, but it had no effect that I can discern.

**Comment by benlieb** [comment]
This is pretty much a dealbreaker for me. Using your other copilot plugin alone gets me results faster, and more often, event when I just enter into the next new line with no text. HAVING to type something, and a whole word at that makes this much less useful. The problem with that though, is that I can't accept the answers, since <Tab> is used by `nvim-cmp`.

Is there a way to manually trigger copilot completions when I want them? Or a way to configure it to trigger on newlines, and on normal text characters (I expect the debounce from copilot.lua will still work)?

I've spent too long on this. Going back to `copilot.vim` for now.

**Comment by zbirenbaum** [comment]
I'm a bit confused here. If you want to have completions manually triggered, thats a cmp feature. You can set a hotkey to fetch completions from a particular source in your cmp config
```
    ["<C-s>"] = cmp.mapping.complete({
        config = {
          sources = {
            { name = 'copilot' },
          }
        }
      }),
```

Also, it seems like your issue is with copilot-cmp, so why swap to copilot.vim when copilot.lua provides all of its features? Is there something here I am missing?

**Comment by qRoC** [comment]
This plugin by default severely restricts trigger.

Just edit `keyword_pattern`:

```lua
{ name = "copilot", keyword_pattern = "." },
```

**Comment by zbirenbaum** [comment]
> This plugin by default severely restricts trigger.
> 
> 
> 
> Just edit `keyword_pattern`:
> 
> 
> 
> ```lua
> 
> { name = "copilot", keyword_pattern = "." },
> 
> ```
> 
> 

I think I may have changed the keyword pattern in the last commit in an effort to address this but it just made things worse. I changed it to '.' just now, so let me know if that fixes the issue here. I'll keep this open until there's some confirmation the problem is fixed or it goes inactive.
