### ISSUE TITLE
I'm only getting one-line suggestions in ruby and javascript, but more in lua

### ISSUE THREAD

**Issue by benlieb** [zbirenbaum/copilot-cmp#57]
When I edit ruby or javascript code, all copilot suggestions are one line long, like.

When I'm in Lua, the suggestions are for entire chunks of code.

Is this a configuration issue on my side? When I used another copilot setup, I got full blocks...

**Comment by guillaumewuip** [comment]
Maybe a duplicates of https://github.com/zbirenbaum/copilot-cmp/issues/10?

**Comment by benlieb** [comment]
Yeah I think this isn't copilot-cmp. Sometimes it gives more.
