### ISSUE TITLE
Suggestions don't take into account lines above

### ISSUE THREAD

**Issue by benlieb** [zbirenbaum/copilot-cmp#58]
When I type:

```javascript
// a function to add two numbers
|
```

And have my cursor where indicated, I get nothing. In other setups I get options.

What am I missing?

**Comment by guillaumewuip** [comment]
Duplicates of https://github.com/zbirenbaum/copilot-cmp/issues/5 maybe?

**Comment by zbirenbaum** [comment]
> Duplicates of #5 maybe?

Yes it is
