### ISSUE TITLE
Using cmp replace behaviour does not fix trailing character

### ISSUE THREAD

**Issue by lars-vc** [zbirenbaum/copilot-cmp#65]
I saw issue #22 and have similar problems, I have the following mapping setup in cmp (this fixed the indent issue #45)
```lua
    ["<Tab>"] = cmp.mapping(function(fallback)
        if cmp.visible() then
            cmp.confirm({ select = true, behavior = cmp.ConfirmBehavior.Replace })
        else
            fallback()
        end
    end, { "i", "c" }),
```

https://user-images.githubusercontent.com/57136208/235096016-f77ef2c3-9783-4abd-a6f5-25c7359616eb.mp4

**Comment by zbirenbaum** [comment]
Please test #67 or checkout the `formatting-fixes` branch and see if it fixes your issue.

**Comment by lars-vc** [comment]
This indeed fixes the issues! I will leave this issue open til the pr is merged, so others can fix this too.
