### ISSUE TITLE
Copilot doesn't show up in cmp

### ISSUE THREAD

**Issue by saladuit** [zbirenbaum/copilot-cmp#71]
I have the following setup, but it doesn't seem to work while ```:Copilot panel``` works:
<img width="663" alt="Screenshot 2023-05-23 at 19 04 38" src="https://github.com/zbirenbaum/copilot-cmp/assets/43225170/4b041f55-889e-4ff3-8761-650468ebeddc">
Setup:
<img width="1463" alt="Screenshot 2023-05-23 at 18 58 25" src="https://github.com/zbirenbaum/copilot-cmp/assets/43225170/fea41c2c-dec4-4db1-ad44-bcb78bab06be">
I've tried many different combinations, but all seem to fail. I would love to get some suggestions/help. 
I've also read #39 but wasn't able to figure it out.

**Comment by saladuit** [comment]
I use astronvim

**Comment by zbirenbaum** [comment]
This is a config issue, the fix in the linked issue should work
