### ISSUE TITLE
[Bug] Doesn't update the completion menu automatically.

### ISSUE THREAD

**Issue by Fau818** [zbirenbaum/copilot-cmp#72]
It looks like this plugin does not automatically update the completion menu.
I have demonstrated this in the following videos with `copilot-cmp` and `cmp-copilot` respectively.

https://github.com/zbirenbaum/copilot-cmp/assets/75115028/c588da49-89fd-4089-a8cb-eb3b8d5a2b70

**Comment by Fau818** [comment]
Just now I tried to set `suggestion.auto_trigger = false` and then I found that the issue was fixed.

I think I share the same problem with #71.

**Comment by saladuit** [comment]
I will definitely try!
