### ISSUE TITLE
Copilot doesn't work

### ISSUE THREAD

**Issue by cxzhou35** [zbirenbaum/copilot-cmp#75]
I have viewed the similar issues in this repo, but none of them worked, so I raise a new issue to ask for help.

I have setup both copilot.lua and copilot-cmp plugins, the config is below(based on LazyVim):

```lua
return {

  -- copilot
  {
    "zbirenbaum/copilot.lua",
    cmd = "Copilot",
    build = ":Copilot auth",
    opts = {
      suggestion = { enabled = false },
      panel = { enabled = false },
      filetypes = {
        markdown = true,
        help = true,
      },
    },
  },
  {
    "nvim-lualine/lualine.nvim",
    optional = true,
    event = "VeryLazy",
    opts = function(_, opts)
      local Util = require("lazyvim.util")
      local colors = {
        [""] = Util.fg("Special"),
        ["Normal"] = Util.fg("Special"),
        ["Warning"] = Util.fg("DiagnosticError"),
        ["InProgress"] = Util.fg("DiagnosticWarn"),
      }
      table.insert(opts.sections.lualine_x, 2, {
        function()
          local icon = require("lazyvim.config").icons.kinds.Copilot
          local status = require("copilot.api").status.data
          return icon .. (status.message or "")
        end,
        cond = function()
          local ok, clients = pcall(vim.lsp.get_active_clients, { name = "copilot", bufnr = 0 })
          return ok and #clients > 0
        end,
        color = function()
          if not package.loaded["copilot"] then
            return
          end
          local status = require("copilot.api").status.data
          return colors[status.status] or colors[""]
        end,
      })
    end,
  },

  -- copilot cmp source
  {
    "nvim-cmp",
    dependencies = {
      {
        "zbirenbaum/copilot-cmp",
        dependencies = "copilot.lua",
        opts = {},
        config = function(_, opts)
          local copilot_cmp = require("copilot_cmp")
          copilot_cmp.setup(opts)
          -- attach cmp source whenever copilot attaches
          -- fixes lazy-loading issues with the copilot cmp source
          require("lazyvim.util").on_attach(function(client)
            if client.name == "copilot" then
              copilot_cmp._on_insert_enter({})
            end
          end)
        end,
      },
    },
    ---@param opts cmp.ConfigSchema
    opts = function(_, opts)
      local cmp = require("cmp")

      table.insert(opts.sources, 1, { name = "copilot", group_index = 2 })

      opts.sorting = {
        priority_weight = 2,
        comparators = {
          require("copilot_cmp.comparators").prioritize,

          -- Below is the default comparitor list and order for nvim-cmp
          cmp.config.compare.offset,
          -- cmp.config.compare.scopes, --this is commented in nvim-cmp too
          cmp.config.compare.exact,
          cmp.config.compare.score,
          cmp.config.compare.recently_used,
          cmp.config.compare.locality,
          cmp.config.compare.kind,
          cmp.config.compare.sort_text,
          cmp.config.compare.length,
          cmp.config.compare.order,
        },
      }
    end,
  },
}
``` 

How to reproduce:

1. Setup LazyVim and install the copilot.lua and copilot-cmp plugins
2. Auth the github account to use the copilot.
3. Edit anyone file with neovim.
4. Copilot doesn't work.

LspInfo result:
<img width="1470" alt="image" src="https://github.com/zbirenbaum/copilot.lua/assets/80182956/fa0b8027-e377-424a-a22d-8d9aa0d78e43">

Lualine Status(The copilot status is online):
<img width="1470" alt="image" src="https://github.com/zbirenbaum/copilot.lua/assets/80182956/02fcbc13-7afb-4a28-92e1-a4d99b035f34">

Anyone can provide the solutions for me? Thanks a lot. :)

**Comment by zbirenbaum** [comment]
It looked like in the post on copilot.lua you had suggestions in the cmp window correct? If that's the case this is working normally.

> But if `copilot.lua` is working as expected, some texts will appear in the context of my code?
> 
> I still can't see any code suggestions provided by `copilot.lua` without the `nvim-cmp` popup window.

Copilot.vim/copilot.lua style inline text suggestions are mutually exclusive with copilot-cmp. This is a limitation brought on by nvim-cmp's ghost text which doesn't support multiline suggestions.

**Comment by cxzhou35** [comment]
> It looked like in the post on copilot.lua you had suggestions in the cmp window correct? If that's the case this is working normally.
> 
> > But if `copilot.lua` is working as expected, some texts will appear in the context of my code?
> > I still can't see any code suggestions provided by `copilot.lua` without the `nvim-cmp` popup window.
> 
> Copilot.vim/copilot.lua style inline text suggestions are mutually exclusive with copilot-cmp. This is a limitation brought on by nvim-cmp's ghost text which doesn't support multiline suggestions.

Sorry, I didn't say it clearly, I disabled the copilot-cmp plugin, and in this case I even can't see any suggestions provided by copilot. Now I can't see any suggestions in both cmp popup window and neovim editor window.

**Comment by cxzhou35** [comment]
I just want the suggestions in the nvim-cmp popup window.

**Comment by zbirenbaum** [comment]
> I just want the suggestions in the nvim-cmp popup window.

Can you check what :LspLog reports? Also can you try removing copilot-cmp and enable suggestions for copilot.lua to see if they appear that way?

**Comment by cxzhou35** [comment]
> > I just want the suggestions in the nvim-cmp popup window.
> 
> Can you check what :LspLog reports? Also can you try removing copilot-cmp and enable suggestions for copilot.lua to see if they appear that way?

I notice that you also reply in the [copilot.lua](https://github.com/zbirenbaum/copilot.lua/issues/180#issuecomment-1595981348), you can find my solution in [this comment](https://github.com/zbirenbaum/copilot.lua/issues/180#issuecomment-1603605328), now the copilot is work, but the integration of cmp still failed.

```lua
return {
  {
    "zbirenbaum/copilot.lua",
    cmd = "Copilot",
    event = "InsertEnter",
    build = ":Copilot auth",
    module = "copilot",
    opts = {
      suggestion = { enabled = false },
      panel = { enabled = false },
      filetypes = {
        yaml = false,
        markdown = false,
        help = false,
        gitcommit = false,
        gitrebase = false,
        hgcommit = false,
        svn = false,
        cvs = false,
      },
    },
  },
  {
    "zbirenbaum/copilot-cmp",
    dependencies = "copilot.lua",
    event = { "InsertEnter", "LspAttach" },
    fix_pairs = true,
    config = function(_, opts)
      local copilot_cmp = require("copilot_cmp")
      copilot_cmp.setup(opts)
      -- attach cmp source whenever copilot attaches
      -- fixes lazy-loading issues with the copilot cmp source
      require("lazyvim.util").on_attach(function(client)
        if client.name == "copilot" then
          copilot_cmp._on_insert_enter({})
        end
      end)
    end,
  },
}
```

**Comment by techcaotri** [comment]
Not sure if it's similar to your issue but I had a similar symptom with 'clangd' and 'ccls' active at the same time: Copilot suggestion was working but the integration of cmp was failed, suggestion not showing the cmp menu.

After digging a bit, I think it's because of the wrong check [here](https://github.com/zbirenbaum/copilot-cmp/blob/c2cdb3c0f5078b0619055af192295830a7987790/lua/copilot_cmp/source.lua#L26)

I made a quick fix and PR [here](https://github.com/zbirenbaum/copilot-cmp/pull/83). Now I can see the copilot suggestion in cmp menu:
![image](https://github.com/zbirenbaum/copilot-cmp/assets/546620/e122d250-1e20-4a73-af29-e097b62c3edc)

Could you check if it also resolves your issue @cxzhou35 

My Neovim version: NVIM v0.10.0-dev-604+gd191bdf9d

P/S: I guess it's also related to issue #78 

> > > I just want the suggestions in the nvim-cmp popup window.
> > 
> > 
> > Can you check what :LspLog reports? Also can you try removing copilot-cmp and enable suggestions for copilot.lua to see if they appear that way?
> 
> I notice that you also reply in the [copilot.lua](https://github.com/zbirenbaum/copilot.lua/issues/180#issuecomment-1595981348), you can find my solution in [this comment](https://github.com/zbirenbaum/copilot.lua/issues/180#issuecomment-1603605328), now the copilot is work, but the integration of cmp still failed.
> 
> ```lua
> return {
>   {
>     "zbirenbaum/copilot.lua",
>     cmd = "Copilot",
>     event = "InsertEnter",
>     build = ":Copilot auth",
>     module = "copilot",
>     opts = {
>       suggestion = { enabled = false },
>       panel = { enabled = false },
>       filetypes = {
>         yaml = false,
>         markdown = false,
>         help = false,
>         gitcommit = false,
>         gitrebase = false,
>         hgcommit = false,
>         svn = false,
>         cvs = false,
>       },
>     },
>   },
>   {
>     "zbirenbaum/copilot-cmp",
>     dependencies = "copilot.lua",
>     event = { "InsertEnter", "LspAttach" },
>     fix_pairs = true,
>     config = function(_, opts)
>       local copilot_cmp = require("copilot_cmp")
>       copilot_cmp.setup(opts)
>       -- attach cmp source whenever copilot attaches
>       -- fixes lazy-loading issues with the copilot cmp source
>       require("lazyvim.util").on_attach(function(client)
>         if client.name == "copilot" then
>           copilot_cmp._on_insert_enter({})
>         end
>       end)
>     end,
>   },
> }
> ```

**Comment by cxzhou35** [comment]
> Not sure if it's similar to your issue but I had a similar symptom with 'clangd' and 'ccls' active at the same time: Copilot suggestion was working but the integration of cmp was failed, suggestion not showing the cmp menu.
> 
> After digging a bit, I think it's because of the wrong check [here](https://github.com/zbirenbaum/copilot-cmp/blob/c2cdb3c0f5078b0619055af192295830a7987790/lua/copilot_cmp/source.lua#L26)
> 
> I made a quick fix and PR [here](https://github.com/zbirenbaum/copilot-cmp/pull/83). Now I can see the copilot suggestion in cmp menu: ![image](https://user-images.githubusercontent.com/546620/255795634-e122d250-1e20-4a73-af29-e097b62c3edc.png)
> 
> Could you check if it also resolves your issue @cxzhou35
> 
> My Neovim version: NVIM v0.10.0-dev-604+gd191bdf9d
> 
> P/S: I guess it's also related to issue #78
> 
> > > > I just want the suggestions in the nvim-cmp popup window.
> > > 
> > > 
> > > Can you check what :LspLog reports? Also can you try removing copilot-cmp and enable suggestions for copilot.lua to see if they appear that way?
> > 
> > 
> > I notice that you also reply in the [copilot.lua](https://github.com/zbirenbaum/copilot.lua/issues/180#issuecomment-1595981348), you can find my solution in [this comment](https://github.com/zbirenbaum/copilot.lua/issues/180#issuecomment-1603605328), now the copilot is work, but the integration of cmp still failed.
> > ```lua
> > return {
> >   {
> >     "zbirenbaum/copilot.lua",
> >     cmd = "Copilot",
> >     event = "InsertEnter",
> >     build = ":Copilot auth",
> >     module = "copilot",
> >     opts = {
> >       suggestion = { enabled = false },
> >       panel = { enabled = false },
> >       filetypes = {
> >         yaml = false,
> >         markdown = false,
> >         help = false,
> >         gitcommit = false,
> >         gitrebase = false,
> >         hgcommit = false,
> >         svn = false,
> >         cvs = false,
> >       },
> >     },
> >   },
> >   {
> >     "zbirenbaum/copilot-cmp",
> >     dependencies = "copilot.lua",
> >     event = { "InsertEnter", "LspAttach" },
> >     fix_pairs = true,
> >     config = function(_, opts)
> >       local copilot_cmp = require("copilot_cmp")
> >       copilot_cmp.setup(opts)
> >       -- attach cmp source whenever copilot attaches
> >       -- fixes lazy-loading issues with the copilot cmp source
> >       require("lazyvim.util").on_attach(function(client)
> >         if client.name == "copilot" then
> >           copilot_cmp._on_insert_enter({})
> >         end
> >       end)
> >     end,
> >   },
> > }
> > ```

Thanks to your detailed reply, I will try your solution and give my results as soon as possible.
