### ISSUE TITLE
copilot rejected from attaching.

### ISSUE THREAD

**Issue by TechDufus** [zbirenbaum/copilot-cmp#77]
![image](https://github.com/zbirenbaum/copilot-cmp/assets/46715299/46e1a472-cc6f-47a4-ac89-49ac412e4b70)

I get this when opening a `.yml` file that my ansible LSP auto-attaches to. I can proc the message from the screenshot by running `:Copilot attach`. 

If I force the attach with `:Copilot! attach` like Copilot suggests, all is well, everything works, hallelujah.. My question is how to `force` auto-attaching like this.... thoughts?

**Comment by MunifTanjim** [comment]
Use the `filetypes` option mentioned here: https://github.com/zbirenbaum/copilot.lua#setup-and-configuration

```lua
require('copilot').setup({
  filetypes = {
    yaml = true,
  },
})
```

**Comment by TechDufus** [comment]
FYI I tried 
```lua
require('copilot').setup({
  filetypes = {
    ['*'] = true,
  },
})
```
but this didn't change anything... Ideally copilot would attach to any open file I have... so I'd assume this would work, but it doesn't.

**Comment by MunifTanjim** [comment]
That should actually work. Not sure why it doesn't for you.

**Comment by TechDufus** [comment]
I'll play with it.. THANK YOU for getting back to me! :)
