### ISSUE TITLE
Not getting suggestions into my cmp

### ISSUE THREAD

**Issue by aneshodza** [zbirenbaum/copilot-cmp#78]
I recently got the issue that the copilot suggestions don't show up in my cmp (but running `:Copilot suggestion` shows what it should):
![gif of it not working](https://github.com/zbirenbaum/copilot-cmp/assets/75726773/6cdf80db-f80c-4f68-bba8-2e191e2c08f5)

My lazy.nvim download:
```
  -- copilot
  {
    "zbirenbaum/copilot.lua",
    event = "InsertEnter",
    opts = overrides.copilot,
  },

  {
    "zbirenbaum/copilot-cmp",
    config = function ()
      require("copilot_cmp").setup()
    end
  },
```
And the cmp groups:
```
  sources = {
    { name = "nvim_lsp", group_index = 2 },
    { name = "copilot",  group_index = 2 },
    { name = "luasnip",  group_index = 2 },
    { name = "buffer",   group_index = 2 },
    { name = "nvim_lua", group_index = 2 },
    { name = "path",     group_index = 2 },
  },
```

For a more detailed look, check out my [nvchad config](github.com/aneshodza/nvchad_config)

`:Copilot status` yields:
```
[Copilot] Online
[Copilot] Enabled for ruby
```

Update: running `:LspLog` shows something interesting:
`The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless`

**Comment by aneshodza** [comment]
I think I solved it: I had steep as an lsp on. That caused copilot to not show in the cmp settings.
Hope this helps someone in the future.

**Comment by skmtkytr** [comment]
@aneshodza 
same trouble now.
Im using Steep LSP too.
How fix this?

**Comment by aneshodza** [comment]
> @aneshodza 
> same trouble now.
> Im using Steep LSP too.
> How fix this?

I think the issue was even that one of my LSPs was crashing (in this case Steep) and that caused it. Make sure you have a Steepfile in the project, that should fix it.

If it doesn't maybe you can investigate further and post your findings. If it's a compatability problem it should be fixed.
