### ISSUE TITLE
Candidates with multiple lines doesn't appear

### ISSUE THREAD

**Issue by MKrbm** [zbirenbaum/copilot-cmp#87]
Usually, if I write a comment like `--function receives list of number and returns their sum`

It generates

![image](https://github.com/zbirenbaum/copilot-cmp/assets/57752203/fb4e4063-c8f9-4c61-bd12-3c7fefe3d72d)

with configs
![image](https://github.com/zbirenbaum/copilot-cmp/assets/57752203/8b9a5143-59d5-4013-9ea8-03fa710674e9)

---

However, if I use copilot-cmp no corresponding shows.

![image](https://github.com/zbirenbaum/copilot-cmp/assets/57752203/56758332-89b3-465f-8bcf-3d89e15fc491)

Instead, only single line will be generated

![image](https://github.com/zbirenbaum/copilot-cmp/assets/57752203/5ea273dd-e9ad-47ac-ba36-818fa548b3ee)

with configs

![image](https://github.com/zbirenbaum/copilot-cmp/assets/57752203/b70e02ba-ea0a-4a37-972e-6e87699b5a8a)

---

How can I generate similarly as I do without copilot-cmp?

**Comment by zbirenbaum** [comment]
Multiline should work out of the box, but I've been noticing a strange occurrence where some multiline completions appear but not others. I think it is something relating to cmp because the completions are provided to it. I'll look into it.

**Comment by MKrbm** [comment]
So is it supposed to generate the same code with normal copilot? Apparently not though.

**Comment by yakiimo23** [comment]
I am experiencing the same problem. I have tried different settings, but the result is the same.

**Comment by zbirenbaum** [comment]
There seems to have been a change in cmp which invalidated a previously working way of specifying ranges for a completion. I have changed formatting to comply with the spec and multiline completions appear again.

**Comment by yakiimo23** [comment]
Multi-line candidates are now displayed! Thank you very much!

![image](https://github.com/zbirenbaum/copilot-cmp/assets/2512785/a2c83617-bb3c-4a69-b9ba-fe2b78c26e5d)
