### ISSUE TITLE
No copilot entries in completion menu

### ISSUE THREAD

**Issue by siddharth99** [zbirenbaum/copilot-cmp#93]
I'm running a very simple LazyVim config with the existing support for copilot.lua (https://www.lazyvim.org/extras/coding/copilot). I am seeing that I get 2 types of completion menu's

1. It shows all the regular sources but not copilot. This appears when I am in the middle of typing a word; please see 1st image.
2. It only shows copilot entries, this appears only when I have completed a word etc; please see 2nd image.

<img width="871" alt="image" src="https://github.com/zbirenbaum/copilot-cmp/assets/3825449/b7729b2d-8ce8-497b-ad2d-2a19dcf69e7b">

<img width="621" alt="image" src="https://github.com/zbirenbaum/copilot-cmp/assets/3825449/e5ebee41-402e-40a3-bfc5-19d8a6fed726">

I have tried the suggestion to explicitly `suggestion.auto_trigger = false` but that didn't help with this issue; I tried all cross-combinations of suggestion.enabled & suggestion.auto_trigger but it seems to be happening regardless.

I am on the latest nvim release 0.9.2 and have all the plugins updated to HEAD yesterday.

**Comment by folke** [comment]
LazyVim used cmp's `group_index` incorrectly, resulting in the behavior you were seeing.
Should be fixed now!

**Comment by siddharth99** [comment]
I can confirm this looks good now, thanks!

**Comment by sekomer** [comment]
I'm using packer, still having this issue, how can I fix it?
